
package com.microsoft.schemas.office.outlook._2006.oms;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "OMS", targetNamespace = "http://schemas.microsoft.com/office/Outlook/2006/OMS", wsdlLocation = "file:/D:/Petrov/NetByNet/ECM/megafon2.wsdl")
public class OMS
    extends Service
{

    private final static URL OMS_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.microsoft.schemas.office.outlook._2006.oms.OMS.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.microsoft.schemas.office.outlook._2006.oms.OMS.class.getResource(".");
            url = new URL(baseUrl, "file:/D:/Petrov/NetByNet/ECM/megafon2.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/D:/Petrov/NetByNet/ECM/megafon2.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        OMS_WSDL_LOCATION = url;
    }

    public OMS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OMS() {
        super(OMS_WSDL_LOCATION, new QName("http://schemas.microsoft.com/office/Outlook/2006/OMS", "OMS"));
    }

    /**
     * 
     * @return
     *     returns OMSSoap
     */
    @WebEndpoint(name = "OMSSoap")
    public OMSSoap getOMSSoap() {
        return super.getPort(new QName("http://schemas.microsoft.com/office/Outlook/2006/OMS", "OMSSoap"), OMSSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OMSSoap
     */
    @WebEndpoint(name = "OMSSoap")
    public OMSSoap getOMSSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://schemas.microsoft.com/office/Outlook/2006/OMS", "OMSSoap"), OMSSoap.class, features);
    }

}
