
package com.microsoft.schemas.office.outlook._2006.oms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "OMSSoap", targetNamespace = "http://schemas.microsoft.com/office/Outlook/2006/OMS")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OMSSoap {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetServiceInfo", action = "http://schemas.microsoft.com/office/Outlook/2006/OMS/GetServiceInfo")
    @WebResult(name = "GetServiceInfoResult", targetNamespace = "http://schemas.microsoft.com/office/Outlook/2006/OMS")
    @RequestWrapper(localName = "GetServiceInfo", targetNamespace = "http://schemas.microsoft.com/office/Outlook/2006/OMS", className = "com.microsoft.schemas.office.outlook._2006.oms.GetServiceInfo")
    @ResponseWrapper(localName = "GetServiceInfoResponse", targetNamespace = "http://schemas.microsoft.com/office/Outlook/2006/OMS", className = "com.microsoft.schemas.office.outlook._2006.oms.GetServiceInfoResponse")
    public String getServiceInfo();

    /**
     * 
     * @param xmsUser
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetUserInfo", action = "http://schemas.microsoft.com/office/Outlook/2006/OMS/GetUserInfo")
    @WebResult(name = "GetUserInfoResult", targetNamespace = "http://schemas.microsoft.com/office/Outlook/2006/OMS")
    @RequestWrapper(localName = "GetUserInfo", targetNamespace = "http://schemas.microsoft.com/office/Outlook/2006/OMS", className = "com.microsoft.schemas.office.outlook._2006.oms.GetUserInfo")
    @ResponseWrapper(localName = "UserInfoResponse", targetNamespace = "http://schemas.microsoft.com/office/Outlook/2006/OMS", className = "com.microsoft.schemas.office.outlook._2006.oms.UserInfoResponse")
    public String getUserInfo(
        @WebParam(name = "xmsUser", targetNamespace = "http://schemas.microsoft.com/office/Outlook/2006/OMS")
        String xmsUser);

    /**
     * 
     * @param xmsData
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendXms", action = "http://schemas.microsoft.com/office/Outlook/2006/OMS/SendXms")
    @WebResult(name = "SendXmsResult", targetNamespace = "http://schemas.microsoft.com/office/Outlook/2006/OMS")
    @RequestWrapper(localName = "SendXms", targetNamespace = "http://schemas.microsoft.com/office/Outlook/2006/OMS", className = "com.microsoft.schemas.office.outlook._2006.oms.SendXms")
    @ResponseWrapper(localName = "SendXmsResponse", targetNamespace = "http://schemas.microsoft.com/office/Outlook/2006/OMS", className = "com.microsoft.schemas.office.outlook._2006.oms.SendXmsResponse")
    public String sendXms(
        @WebParam(name = "xmsData", targetNamespace = "http://schemas.microsoft.com/office/Outlook/2006/OMS")
        String xmsData);

    /**
     * 
     * @param xmsData
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DeliverXms", action = "http://schemas.microsoft.com/office/Outlook/2006/OMS/DeliverXms")
    @WebResult(name = "DeliverXmsResult", targetNamespace = "http://schemas.microsoft.com/office/Outlook/2006/OMS")
    @RequestWrapper(localName = "DeliverXms", targetNamespace = "http://schemas.microsoft.com/office/Outlook/2006/OMS", className = "com.microsoft.schemas.office.outlook._2006.oms.DeliverXms")
    @ResponseWrapper(localName = "DeliverXmsResponse", targetNamespace = "http://schemas.microsoft.com/office/Outlook/2006/OMS", className = "com.microsoft.schemas.office.outlook._2006.oms.DeliverXmsResponse")
    public String deliverXms(
        @WebParam(name = "xmsData", targetNamespace = "http://schemas.microsoft.com/office/Outlook/2006/OMS")
        String xmsData);

}
